### ISSUE TITLE
MySQL Error : Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by krak3n** [pcraciunoiu/django-nginx-memcache#3]
Hi

When running syncdb on a MySQL server with a UTF-8 character set the index in the create table SQL results in the index exceeding the 1000 bytes limit. This is because UTF-8 uses 3 bytes per character instead of 1 (in Latin1 for example). It means that your UNIQUE index exceeds the 1000 byte limit in this situation.

I think this is something the MySQL team are looking at but don't think has been resolved yet (at least in the MySQL i'm running which is 5.1.41).

I have to use a UTF-8 character set as I am dealing with multiple languages.

Thanks,

Chris

**Comment by pcraciunoiu** [comment]
But this project doesn't have any tables... so I'm a bit unclear on how it's creating any?

**Comment by krak3n** [comment]
Ah, apologies, I meant this issue for this forked version: https://github.com/torchbox/django-nginx-memcache

Chris

**Comment by pcraciunoiu** [comment]
I'm working with Steve on merging his changes over here but we've both been pretty busy.

@stevejalim: I assigned this to you if you don't mind. Feel free to file a pull request once it's ready for review.

**Comment by stevejalim** [comment]
Hi Chris

I've just pushed to my fork. I've reduced the length of the supplementary_identifier column to 45 chars, which I hope fixes things (no time to set up a MySQL DB here right now - I only trust Postgres these days). 

So, 45 + 255 + 32 \* gives us 996 chars, which I hope works for you, even if the index name is concatenated with a '_' between each.

Let me know how you get on - best to raise a ticket on my fork, for now, I think

Steve

**Comment by krak3n** [comment]
Thanks Steve, i'll try this now. 

Chris 

---

Chris Reeves
Python / Django Web Developer & lover of digital things.
Twitter: @krak3n (https://twitter.com/krak3n)
Github: https://github.com/krak3n

**Comment by krak3n** [comment]
This is now resolved, thanks guys :)

**Comment by pcraciunoiu** [comment]
Excellent.

Hey Steve,
Do you want to file a pull request for me to merge this stuff? I forget if you already did.
